# Brun Homebrew dependencies
# Install only brew packages:
#   brew bundle --file=~/.brun/Brewfile
#
# If Homebrew requires tap trust (Homebrew 6+):
#   brew tap FelixKratz/formulae
#   brew trust FelixKratz/formulae

tap "FelixKratz/formulae"
tap "borgbackup/tap"
tap "shopify/shopify"

# CLI / development tools
brew "git"
brew "node"
brew "npm"
brew "tmux"
brew "neovim"
brew "coreutils"
brew "stow"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zplug"
brew "fzf"
brew "bat"
brew "fd"
brew "pv"
brew "zoxide"
brew "lua"
brew "luajit"
brew "luarocks"
brew "prettier"
brew "make"
brew "lazygit"
brew "lazydocker"
brew "tree-sitter"
brew "tree"
brew "watch"
brew "borders"
brew "imagemagick"
brew "ffmpeg"
brew "htop"
brew "btop"
brew "borgbackup"
brew "xcodes"
brew "shopify-cli"
brew "dockutil"
brew "watchman"
brew "cocoapods"
brew "awscli"
brew "mysql-client"
brew "composer"
brew "borgbackup/tap/borgbackup-fuse"

# Apps
cask "gcloud-cli"
cask "docker-desktop"
cask "zulu@17"
cask "android-studio"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-sf-pro"
cask "google-chrome"
cask "spotify"
cask "iterm2"
cask "tableplus"
cask "phpstorm"
cask "cursor"
cask "1password"
cask "discord"
cask "notion"
cask "anydesk"
cask "postman"
cask "bruno"
cask "requestly"
cask "ngrok"
cask "libreoffice"
cask "vlc"
cask "macfuse"
cask "vorta"
cask "ollama-app"
cask "openlogi"
cask "the-unarchiver"
cask "whatsapp"
cask "telegram"
cask "rectangle"
cask "slack"
cask "blender"
cask "unity"
cask "rider"
cask "steam"
cask "claude-code"
cask "opencode"
cask "rustdesk"
cask "utm"
cask "lm-studio"
