# Brun Homebrew dependencies
# Install only brew packages:
#   brew bundle --file=~/.brun/Brewfile
#
# If Homebrew requires tap trust (Homebrew 6+):
#   brew tap FelixKratz/formulae
#   brew trust FelixKratz/formulae

tap "FelixKratz/formulae"
tap "borgbackup/tap"
tap "shopify/shopify"

# CLI / development tools
brew "git"
brew "node"
brew "npm"
brew "tmux"
brew "neovim"
brew "coreutils"
brew "stow"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zplug"
brew "fzf"
brew "bat"
brew "fd"
brew "zoxide"
brew "lua"
brew "luajit"
brew "luarocks"
brew "prettier"
brew "make"
brew "lazygit"
brew "lazydocker"
brew "tree-sitter"
brew "tree"
brew "borders"
brew "imagemagick"
brew "htop"
brew "btop"
brew "borgbackup"
brew "xcodes"
brew "shopify-cli"
brew "dockutil"
brew "watchman"
brew "cocoapods"
brew "borgbackup/tap/borgbackup-fuse"

# Apps
cask "docker-desktop"
cask "zulu@17"
cask "android-studio"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-sf-pro"
cask "google-chrome"
cask "spotify"
cask "iterm2"
cask "tableplus"
cask "phpstorm"
cask "cursor"
cask "1password"
cask "discord"
cask "notion"
cask "anydesk"
cask "postman"
cask "macfuse"
cask "vorta"
cask "ollama-app"
cask "openlogi"
cask "the-unarchiver"
cask "whatsapp"
cask "rectangle"
cask "slack"
